[compiler]
ldflags = []
cc = "g++"

[compiler.release]
cdefs = ["-DNDEBUG"]
cflags = ["-O2", "-std=c++20", "-pthread", "-static"]

[compiler.linux]
libs = []

[compiler.windows]
libs = []

[compiler.debug]
cdefs = ["-DDEBUG"]
cflags = ["-g", "-Wall", "-std=c++20", "-pthread", "-static"]

[paths]
obj = "./obj"
lib = "./lib"
include = "./include"
bin = "./bin"
src = "./src"

[project]
version = "0.9.3"
type = "program"
name = "cpb"

