[project]
name = "cpb"
type = "program"

[compiler]
cc = "g++"
ldflags = []
libs = []

[compiler.release]
cflags = ["-std=c++20", "-O2", "-static"]
cdefs = ["-DNDEBUG"]

[compiler.debug]
cflags = ["-std=c++20", "-g", "-Wall"]
cdefs = ["-DDEBUG"]

[paths]
src = "./src"
include = "./include"
lib = "./lib"
bin = "./bin"
obj = "./obj"