[project]
name = "cpb"
type = "program"

[compiler]
cc = "g++"
ldflags = []
libs = []

[compiler.release]
cflags = ["-O2", "-std=c++20", "-pthread", "-static"]
cdefs = ["-DNDEBUG"]

[compiler.debug]
cflags = ["-g", "-Wall", "-std=c++20", "-pthread", "-static"]
cdefs = ["-DDEBUG"]

[paths]
src = "./src"
include = "./include"
lib = "./lib"
bin = "./bin"
obj = "./obj"

