[project]
name = "cpb"
type = "program"
version = "0.8.8"

[paths]
src = "./src"
bin = "./bin"
include = "./include"
lib = "./lib"
obj = "./obj"

[compiler]
cc = "g++"
ldflags = []

[compiler.windows]
libs = []

[compiler.linux]
libs = []

[compiler.release]
cflags = ["-O2", "-std=c++20", "-pthread", "-static"]
cdefs = ["-DNDEBUG"]

[compiler.debug]
cflags = ["-g", "-Wall", "-std=c++20", "-pthread", "-static"]
cdefs = ["-DDEBUG"]

